version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "projeto_db"
    ports:
      - "3306:3306"
    volumes:
      - "./database:/var/lib/mysql"
    restart: always