version: '3.8'

services:
  laravel-app:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    expose:
      - '8000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - './app:/app'