version: '3.8'

services:
  php-apache:
    container_name: php-apache
    build: .
    ports:
      - '80:80'
      - '3000:3000'
    expose: 
      - '80'
      - '3000'
    volumes:
      - '.:/var/www/html'
    
    