version: '3.8'

services:
  php-apache:
    container_name: php-apache
    build: .
    ports:
      - '80:80'
      - '8080:8080'
    expose: 
      - '80'
      - '8080'
    volumes:
      - '.:/var/www/html'
    command: php -S 0.0.0.0:8080 -t public
    
    